// src/components/Dish.vue
<template>
  <div className="food-card">
    <div className="menu-card">
      <div className="menu-image" :style="{ 'background-image': image }"></div>
      <div className="menu-title">
        <h5>{{dish.name}}</h5>
      </div>
      <div className="description-frame">
        <p className="menu-description">{{dish.description}}</p>
      </div>
      <div className="plus-icon"></div>
    </div>
  </div>
</template>

<script lang="ts">
import { convertNumberArrayToImageUrl } from '../utils'

export default ({
  props: {
    dish: {} as Dish
  },
  setup (props: { dish: Dish }) {
    const image = convertNumberArrayToImageUrl(props.dish.image)
    return { image }
  }
})
</script>

// src/components/Dish.tsx
import { IDish } from "../types";
import { convertNumberArrayToImageUrl } from "../utils";
import "./Dish.css";

export default function Dish(props: IDish) {
	return (
    <div className="food-card">
      <div className="menu-card">
          <div className="menu-image" style={{backgroundImage: convertNumberArrayToImageUrl(props.image)}}></div>
          <div className="menu-title">
            <h5>{props.name}</h5>
          </div>
          <div className="description-frame">
            <p className="menu-description">{props.description}</p>
          </div>
          <div className="plus-icon"></div>
      </div>
    </div>
	)
}
